/// The slice of `ActivationRegistry` this package calls.
///
/// Written out rather than imported from `packages/contracts/out/`, because
/// that directory is a build artifact: it is gitignored, absent on a fresh
/// clone, and regenerated by `forge build`. A runtime path into it would make
/// this package fail depending on whether somebody had compiled the contracts,
/// which is a worse failure than a stale constant.
///
/// The staleness risk that creates is covered by `abi.test.ts`, which reads the
/// Solidity source and asserts every signature here still matches. That test
/// fails loudly rather than letting a renamed parameter reach a transaction.

export const ACTIVATION_REGISTRY_ABI = [
  {
    type: "function",
    name: "submitParcel",
    stateMutability: "nonpayable",
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "parcelHash", type: "bytes32" },
      { name: "documentsHash", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "recordDecision",
    stateMutability: "nonpayable",
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "decisionHash", type: "bytes32" },
      { name: "engineVersion", type: "string" },
      { name: "verdict", type: "uint8" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "recordCarrier",
    stateMutability: "nonpayable",
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "carrierRefHash", type: "bytes32" },
      { name: "carrierRawHash", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "activations",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [
      { name: "parcelHash", type: "bytes32" },
      { name: "documentsHash", type: "bytes32" },
      { name: "decisionHash", type: "bytes32" },
      { name: "carrierRefHash", type: "bytes32" },
      { name: "carrierRawHash", type: "bytes32" },
      { name: "engineVersion", type: "string" },
      { name: "submittedAt", type: "uint64" },
      { name: "activatedAt", type: "uint64" },
      { name: "attempt", type: "uint32" },
      { name: "verdict", type: "uint8" },
    ],
  },
  {
    type: "function",
    name: "verdictOf",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "", type: "uint8" }],
  },
  {
    type: "function",
    name: "entitlement",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
] as const;

/// `ServiceEntitlement.stateOf`, needed to explain a revert before causing one.
export const SERVICE_ENTITLEMENT_ABI = [
  {
    type: "function",
    name: "stateOf",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "", type: "uint8" }],
  },
  {
    type: "function",
    name: "ownerOf",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "totalMinted",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
] as const;

/// Mirrors `EntitlementState` in `RouteLockTypes.sol`, ordinals included.
///
/// Held here so a revert can be explained in the contract's own vocabulary
/// rather than as a bare `NotUnderReview()`. Parity with the Solidity source is
/// asserted in `abi.test.ts`.
export enum EntitlementState {
  None = 0,
  Available = 1,
  PendingReview = 2,
  Activated = 3,
  LabelCreated = 4,
  InTransit = 5,
  Delivered = 6,
  Remedied = 7,
  Expired = 8,
}

export const ENTITLEMENT_STATE_NAMES: Readonly<Record<EntitlementState, string>> = {
  [EntitlementState.None]: "None",
  [EntitlementState.Available]: "Available",
  [EntitlementState.PendingReview]: "PendingReview",
  [EntitlementState.Activated]: "Activated",
  [EntitlementState.LabelCreated]: "LabelCreated",
  [EntitlementState.InTransit]: "InTransit",
  [EntitlementState.Delivered]: "Delivered",
  [EntitlementState.Remedied]: "Remedied",
  [EntitlementState.Expired]: "Expired",
};
